package constants

const (
	MAPLE_VERSION           = 28
	CLIENT_HEADER_SIZE      = 4
	INTERSERVER_HEADER_SIZE = 4
	OPCODE_LENGTH           = 1

	// Opcodes Server -> Client
	LOGIN_RESPONCE          = 0x01
	LOGIN_WORLD_META        = 0x03
	LOGIN_PIN_REGISTER      = 0x07 // Add 1 byte, 1 = register a pin
	LOGIN_PIN_STUFF         = 0x08 // Setting pin good
	LOGIN_SEND_WORLD_LIST   = 0x09
	LOGIN_CHARACTER_DATA    = 0x0A
	LOGIN_NAME_CHECK_RESULT = 0x0C

	LOGIN_CANNOT_ENTER_WORLD = 0x0B

	// Opcodes Client -> Server
	LOGIN_REQUEST          = 0x01
	LOGIN_CHANNEL_SELECT   = 0x04
	LOGIN_WORLD_SELECT     = 0x05
	LOGIN_CHECK_LOGIN      = 0x08
	LOGIN_CREATE_CHARACTER = 0x09
	LOGIN_SELECT_CHARACTER = 0x0B
	LOGIN_NAME_CHECK       = 0x0D
	LOGIN_NEW_CHARACTER    = 0x0E
)
