package constants

const (
	MOB_SKILL_WEAPON_ATTACK_UP      = 100
	MOB_SKILL_WEAPON_ATTACK_UP_AOE  = 110
	MOB_SKILL_MAGIC_ATTACK_UP       = 101
	MOB_SKILL_MAGIC_ATTACK_UP_AOE   = 111
	MOB_SKILL_WEAPON_DEFENSE_UP     = 102
	MOB_SKILL_WEAPON_DEFENSE_UP_AOE = 112
	MOB_SKILL_MAGIC_DEFENSE_UP      = 103
	MOB_SKILL_MAGIC_DEFENSE_UP_AOE  = 113
	MOB_SKILL_HEAL_AOE              = 114
	MOB_SKILL_SPEED_UP_AOE          = 115
	MOB_SKILL_SEAL                  = 120
	MOB_SKILL_DARKNESS              = 121
	MOB_SKILL_WEAKNESS              = 122
	MOB_SKILL_STUN                  = 123
	MOB_SKILL_CURSE                 = 124
	MOB_SKILL_POISON                = 125
	MOB_SKILL_SLOW                  = 126
	MOB_SKILL_DISPEL                = 127
	MOB_SKILL_SEDUCE                = 128
	MOB_SKILL_SEND_TO_TOWN          = 129
	MOB_SKILL_POISON_MIST           = 131
	MOB_SKILL_CRAZY_SKULL           = 132
	MOB_SKILL_ZOMBIFY               = 133
	MOB_SKILL_WEAPON_IMMUNITY       = 140
	MOB_SKILL_MAGIC_IMMUNITY        = 141
	MOB_SKILL_ARMOR_SKILL           = 142
	MOB_SKILL_WEAPON_DAMAGE_REFLECT = 143
	MOB_SKILL_MAGIC_DAMAGE_REFLECT  = 144
	MOB_SKILL_ANY_DAMAGE_REFLECT    = 145
	MOB_SKILL_MC_WEAPON_ATTACK_UP   = 150
	MOB_SKILL_MC_MAGIC_ATTACK_UP    = 151
	MOB_SKILL_MC_WEAPON_DEFENSE_UP  = 152
	MOB_SKILL_MC_MAGIC_DEFENSE_UP   = 153
	MOB_SKILL_MC_ACCURACY_UP        = 154
	MOB_SKILL_MC_AVOID_UP           = 155
	MOB_SKILL_MC_SPEED_UP           = 156
	MOB_SKILL_MC_SEAL               = 157 // Not actually used in Monster Carnival
	MOB_SKILL_SUMMON                = 200
)
