version: '3.1'

x-common-env: &common_env
    # ===== DATABASE =====
    VALHALLA_DATABASE_ADDRESS: "db"
    VALHALLA_DATABASE_PORT: "3306"
    VALHALLA_DATABASE_USER: "root"
    VALHALLA_DATABASE_PASSWORD: "password"
    VALHALLA_DATABASE_DATABASE: "maplestory"

    # ===== LOGIN =====
    VALHALLA_LOGIN_CLIENTLISTENADDRESS: "0.0.0.0"
    VALHALLA_LOGIN_CLIENTLISTENPORT: "8484"
    VALHALLA_LOGIN_SERVERLISTENADDRESS: "0.0.0.0"
    VALHALLA_LOGIN_SERVERLISTENPORT: "8485"
    VALHALLA_LOGIN_WITHPIN: "true"
    VALHALLA_LOGIN_PACKETQUEUESIZE: "512"
    VALHALLA_LOGIN_LATENCY: "0"
    VALHALLA_LOGIN_JITTER: "0"

    # ===== WORLD =====
    VALHALLA_WORLD_MESSAGE: "message"
    VALHALLA_WORLD_RIBBON: "2"
    VALHALLA_WORLD_EXPRATE: "1.0"
    VALHALLA_WORLD_DROPRATE: "1.0"
    VALHALLA_WORLD_MESOSRATE: "1.0"
    VALHALLA_WORLD_LOGINADDRESS: "login_server"
    VALHALLA_WORLD_LOGINPORT: "8485"
    VALHALLA_WORLD_LISTENADDRESS: "0.0.0.0"
    VALHALLA_WORLD_LISTENPORT: "8584"
    VALHALLA_WORLD_PACKETQUEUESIZE: "512"

    # ===== CASHSHOP =====
    VALHALLA_CASHSHOP_WORLDADDRESS: "world_server"
    VALHALLA_CASHSHOP_WORLDPORT: "8584"
    VALHALLA_CASHSHOP_LISTENADDRESS: "0.0.0.0"
    VALHALLA_CASHSHOP_LISTENPORT: "8600"
    VALHALLA_CASHSHOP_CLIENTCONNECTIONADDRESS: "127.0.0.1"
    VALHALLA_CASHSHOP_PACKETQUEUESIZE: "512"
    VALHALLA_CASHSHOP_LATENCY: "0"
    VALHALLA_CASHSHOP_JITTER: "0"

    # ===== CHANNEL =====
    VALHALLA_CHANNEL_WORLDADDRESS: "world_server"
    VALHALLA_CHANNEL_WORLDPORT: "8584"
    VALHALLA_CHANNEL_LISTENADDRESS: "0.0.0.0"
    VALHALLA_CHANNEL_CLIENTCONNECTIONADDRESS: "127.0.0.1"
    VALHALLA_CHANNEL_PACKETQUEUESIZE: "512"
    VALHALLA_CHANNEL_MAXPOP: "250"


services:
    login_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: login-server
        command: ["/app/Valhalla", "-type", "login"]
        restart: unless-stopped
        volumes:
            - ./docker/docker_config_login.toml:/app/docker/docker_config_login.toml
            - ./Data.nx:/app/Data.nx
        ports:
            - 8484:8484
        depends_on:
            - db
        environment:
            <<: *common_env

    world_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: world-server
        command: ["/app/Valhalla", "-type", "world"]
        restart: unless-stopped
        volumes:
            - ./docker/docker_config_world.toml:/app/docker/docker_config_world.toml
            - ./Data.nx:/app/Data.nx
        ports:
            - 8584:8584
        depends_on:
            - login_server
        environment:
            <<: *common_env

    cashshop_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cashshop-server
        command: ["/app/Valhalla", "-type", "cashshop"]
        restart: unless-stopped
        volumes:
            - ./docker/docker_config_cashshop.toml:/app/docker/docker_config_cashshop.toml
            - ./Data.nx:/app/Data.nx
        ports:
            - 8600:8600
        depends_on:
            - world_server
        environment:
            <<: *common_env

    channel_server_1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: channel-server-1
        command: ["/app/Valhalla", "-type", "channel"]
        restart: unless-stopped
        volumes:
            - ./docker/docker_config_channel_1.toml:/app/docker/docker_config_channel.toml
            - ./Data.nx:/app/Data.nx
        ports:
            - 8685:8685
        depends_on:
            - world_server
        environment:
            <<: *common_env
            VALHALLA_CHANNEL_LISTENPORT: "8685"

    channel_server_2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: channel-server-2
        command: ["/app/Valhalla", "-type", "channel"]
        restart: unless-stopped
        volumes:
            - ./docker/docker_config_channel_2.toml:/app/docker/docker_config_channel.toml
            - ./Data.nx:/app/Data.nx
        ports:
            - 8686:8686
        depends_on:
            - world_server
        environment:
            <<: *common_env
            VALHALLA_CHANNEL_LISTENPORT: "8686"

    db:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: maplestory
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: db
            ADMINER_DEFAULT_DB_NAME: maplestory
            ADMINER_DESIGN: nette
        ports:
            - 8080:8080
        depends_on:
            - db

    prometheus:
        image: prom/prometheus:master
        restart: unless-stopped
        volumes:
            - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana:6.7.3
        restart: unless-stopped
        # environment:
        #     GF_INSTALL_PLUGINS: ""
        ports:
            - 3000:3000

volumes:
    db-data:
