---
apiVersion: v1
kind: ConfigMap
metadata:
  name: login-config
  namespace: {{ .Release.Namespace }}
data:
  config_login.toml: |
    [database]
    address = "{{ .Values.mysql.host }}"
    port = "{{ .Values.mysql.port }}"
    user = "{{ .Values.mysql.user }}"
    password = "{{ .Values.mysql.password }}"
    database = "{{ .Values.mysql.database }}"

    [login]
    clientListenAddress = "0.0.0.0"
    clientListenPort = "8484"
    serverListenAddress = "0.0.0.0"
    serverListenPort = "8485"
    withPin = {{ .Values.login.withPin }}
    autoRegister = {{ .Values.login.autoRegister }}
    packetQueueSize = {{ .Values.login.packetQueueSize }}
    latency = {{ .Values.login.latency }}
    jitter = {{ .Values.login.jitter }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: world-config
  namespace: {{ .Release.Namespace }}
data:
  config_world.toml: |
    [database]
    address = "{{ .Values.mysql.host }}"
    port = "{{ .Values.mysql.port }}"
    user = "{{ .Values.mysql.user }}"
    password = "{{ .Values.mysql.password }}"
    database = "{{ .Values.mysql.database }}"

    [world]
    message = "{{ .Values.world.message }}"
    ribbon = {{ .Values.world.ribbon }}
    expRate = {{ .Values.world.expRate }}
    dropRate = {{ .Values.world.dropRate }}
    mesosRate = {{ .Values.world.mesosRate }}
    loginAddress = "login-server.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    loginPort = "8485"
    listenAddress = "0.0.0.0"
    listenPort = "8584"
    packetQueueSize = {{ .Values.world.packetQueueSize }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cashshop-config
  namespace: {{ .Release.Namespace }}
data:
  config_cashshop.toml: |
    [database]
    address = "{{ .Values.mysql.host }}"
    port = "{{ .Values.mysql.port }}"
    user = "{{ .Values.mysql.user }}"
    password = "{{ .Values.mysql.password }}"
    database = "{{ .Values.mysql.database }}"

    [cashshop]
    worldAddress = "world-server.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    worldPort = "8584"
    listenAddress = "0.0.0.0"
    listenPort = "8600"
    clientConnectionAddress = "{{ .Values.cashshop.clientConnectionAddress }}"
    packetQueueSize = {{ .Values.cashshop.packetQueueSize }}
    latency = {{ .Values.cashshop.latency }}
    jitter = {{ .Values.cashshop.jitter }}
{{- $root := . -}}
{{ $replicas := int .Values.channel.replicas -}}
{{- range $i, $_ := until $replicas }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: channel-config-{{ add $i 1 }}
  namespace: {{ $root.Release.Namespace }}
data:
  config_channel.toml: |
    [database]
    address = "{{ $root.Values.mysql.host }}"
    port = "{{ $root.Values.mysql.port }}"
    user = "{{ $root.Values.mysql.user }}"
    password = "{{ $root.Values.mysql.password }}"
    database = "{{ $root.Values.mysql.database }}"

    [channel]
    worldAddress = "world-server.{{ $root.Release.Namespace }}.svc.{{ $root.Values.clusterDomain }}"
    worldPort = "8584"
    listenAddress = "0.0.0.0"
    listenPort = "{{ sub 8685 $i }}"
    clientConnectionAddress = "{{ $root.Values.channel.clientConnectionAddress }}"
    packetQueueSize = {{ $root.Values.channel.packetQueueSize }}
    maxPop = {{ $root.Values.channel.maxPop }}
    latency = {{ $root.Values.channel.latency }}
    jitter = {{ $root.Values.channel.jitter }}
{{- end }}