[database]
address = "db"
port = "3306"
user = "root"
password = "password"
database = "maplestory"

[login]
clientListenAddress = "0.0.0.0"
clientListenPort = "8484"
serverListenAddress = "0.0.0.0"
serverListenPort = "8485"
withPin = true
autoRegister = false
packetQueueSize = 512
