[database]
address = "db"
port = "3306"
user = "root"
password = "password"
database = "maplestory"

[cashshop]
worldAddress = "world_server"
worldPort = "8584"
listenAddress = "0.0.0.0"
listenPort = "8600"
clientConnectionAddress = "127.0.0.1"
packetQueueSize = 512
# The following should be set to zero when not testing on a local network environment
latency = 0
jitter = 0
